import { Component, OnInit } from '@angular/core';
import { IonApp, IonRouterOutlet, IonSplitPane } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  locationOutline,
  location,
  navigateOutline,
  navigate,
  flashOutline,
  flash,
  mapOutline,
  map,
  listOutline,
  list,
  filterOutline,
  filter,
  searchOutline,
  search,
  closeOutline,
  close,
  chevronForward,
  chevronBack,
  informationCircleOutline,
  informationCircle,
  callOutline,
  call,
  globeOutline,
  globe,
  timeOutline,
  time,
  pricetagOutline,
  pricetag,
  warningOutline,
  warning,
  checkmarkCircleOutline,
  checkmarkCircle,
  closeCircleOutline,
  closeCircle,
  helpCircleOutline,
  helpCircle,
  carOutline,
  car,
  batteryChargingOutline,
  batteryCharging,
  speedometerOutline,
  speedometer,
  locateOutline,
  locate,
  refreshOutline,
  refresh,
  shareOutline,
  share,
  starOutline,
  star,
  heartOutline,
  heart,
  menuOutline,
  menu,
  settingsOutline,
  settings,
  homeOutline,
  home,
  newspaperOutline,
  newspaper
} from 'ionicons/icons';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [IonApp, IonRouterOutlet],
  template: `
    <ion-app>
      <ion-router-outlet></ion-router-outlet>
    </ion-app>
  `
})
export class AppComponent implements OnInit {

  constructor() {
    // Register all icons used in the app
    addIcons({
      'location-outline': locationOutline,
      'location': location,
      'navigate-outline': navigateOutline,
      'navigate': navigate,
      'flash-outline': flashOutline,
      'flash': flash,
      'map-outline': mapOutline,
      'map': map,
      'list-outline': listOutline,
      'list': list,
      'filter-outline': filterOutline,
      'filter': filter,
      'search-outline': searchOutline,
      'search': search,
      'close-outline': closeOutline,
      'close': close,
      'chevron-forward': chevronForward,
      'chevron-back': chevronBack,
      'information-circle-outline': informationCircleOutline,
      'information-circle': informationCircle,
      'call-outline': callOutline,
      'call': call,
      'globe-outline': globeOutline,
      'globe': globe,
      'time-outline': timeOutline,
      'time': time,
      'pricetag-outline': pricetagOutline,
      'pricetag': pricetag,
      'warning-outline': warningOutline,
      'warning': warning,
      'checkmark-circle-outline': checkmarkCircleOutline,
      'checkmark-circle': checkmarkCircle,
      'close-circle-outline': closeCircleOutline,
      'close-circle': closeCircle,
      'help-circle-outline': helpCircleOutline,
      'help-circle': helpCircle,
      'car-outline': carOutline,
      'car': car,
      'battery-charging-outline': batteryChargingOutline,
      'battery-charging': batteryCharging,
      'speedometer-outline': speedometerOutline,
      'speedometer': speedometer,
      'locate-outline': locateOutline,
      'locate': locate,
      'refresh-outline': refreshOutline,
      'refresh': refresh,
      'share-outline': shareOutline,
      'share': share,
      'star-outline': starOutline,
      'star': star,
      'heart-outline': heartOutline,
      'heart': heart,
      'menu-outline': menuOutline,
      'menu': menu,
      'settings-outline': settingsOutline,
      'settings': settings,
      'home-outline': homeOutline,
      'home': home,
      'newspaper-outline': newspaperOutline,
      'newspaper': newspaper
    });
  }

  ngOnInit(): void {
    console.log('ElectricMap Bogotá initialized');
  }
}
